include:
  - docker-compose.dependencies.yaml

services:

  # ====Pull-request related services==============================================================
  # ....Test logic related to libpointmatcher install casses.......................................
  _test_compilation:
    image: ${NBS_DOCKERHUB_NAMESPACE:?err}/libpointmatcher-compilation-test:${NBS_IMAGE_TAG:?err}
    pull_policy: build
    build:
      context: ..
      dockerfile: ${NBS_SUPERPROJECT_BUILD_SYSTEM_DIR:?err}/ubuntu/Dockerfile.libpointmatcher.compilation_test
      no_cache: true
      target: test-compilation-auto-path-resolution
      ## Mute 'platforms' while using arch virtualization with C++ build to prevent segmentation fault during lpm cmake install
#      platforms:
#        - "linux/amd64"
#        - "linux/arm64/v8"
      args:
        PROJECT_HUB: ${NBS_DOCKERHUB_NAMESPACE}
        BASE_IMAGE: libpointmatcher-dependencies-general
        BASE_IMAGE_TAG: ${NBS_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        REPOSITORY_VERSION: 'latest'
        CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE:?err}
        INSTALL_SCRIPT_FLAG: '--build-system-CI-install'
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
    depends_on:
      - dependencies-general
  test_compilation_prefixed_path:
    extends: _test_compilation
    build:
      target: test-compilation-prefixed-path
    depends_on:
      - _test_compilation
  test_compilation_auto_path_resolution:
    extends: _test_compilation
    build:
      target: test-compilation-auto-path-resolution
    depends_on:
      - _test_compilation

  # ....Test logic related to libpointmatcher codebase unit-test...................................
  ci_PR:
    image: ${NBS_DOCKERHUB_NAMESPACE:?err}/libpointmatcher-ci-pr:${NBS_IMAGE_TAG:?err}
    pull_policy: build
    build:
      context: ..
      dockerfile: ${NBS_SUPERPROJECT_BUILD_SYSTEM_DIR}/ubuntu/Dockerfile.libpointmatcher.ci_PR
      no_cache: true
      args:
        PROJECT_HUB: ${NBS_DOCKERHUB_NAMESPACE}
        BASE_IMAGE: libpointmatcher-dependencies
        BASE_IMAGE_TAG: ${NBS_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        REPOSITORY_VERSION: 'latest'
        CMAKE_BUILD_TYPE: ${CMAKE_BUILD_TYPE:?err}
        INSTALL_SCRIPT_FLAG: '--build-system-CI-install --compile-test'
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
    depends_on:
      - dependencies
  ci_PR_amd64:
    extends: ci_PR
    build:
      platforms:
        - "linux/amd64"
  ci_PR_arm64v8:
    extends: ci_PR
    build:
      platforms:
        - "linux/arm64/v8"

  # ====Dockerhub release image====================================================================
  release:
    image: ${NBS_DOCKERHUB_NAMESPACE:?err}/libpointmatcher:${NBS_IMAGE_TAG:?err}
    container_name: libpointmatcher
    build:
      context: ..
      dockerfile: ${NBS_SUPERPROJECT_BUILD_SYSTEM_DIR}/ubuntu/Dockerfile.libpointmatcher.hub_release
      platforms:
        - "linux/amd64"
        - "linux/arm64/v8"
      no_cache: true
      args:
        PROJECT_HUB: ${NBS_DOCKERHUB_NAMESPACE}
        BASE_IMAGE: libpointmatcher-dependencies-doc
        BASE_IMAGE_TAG: ${NBS_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        REPOSITORY_VERSION: ${REPOSITORY_VERSION:?err}
        CMAKE_BUILD_TYPE: 'Release'
        INSTALL_SCRIPT_FLAG: '--compile-test --generate-doc'
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
    depends_on:
      - dependencies
      - dependencies-doc


