services:
  dependencies:
    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher-dependencies:${LPM_IMAGE_TAG:?err}
    build:
      context: ..
      dockerfile: ./build_system/ubuntu/Dockerfile.dependencies
      platforms:
        - "linux/amd64"
        - "linux/arm64/v8"
      args:
        BASE_IMAGE: ${DEPENDENCIES_BASE_IMAGE:?err}
        BASE_IMAGE_TAG: ${DEPENDENCIES_BASE_IMAGE_TAG:?err}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        LPM_INSTALLED_LIBRARIES_PATH: ${LPM_INSTALLED_LIBRARIES_PATH:?err}
        LPM_LIBPOINTMATCHER_SRC_REPO_NAME: ${LPM_LIBPOINTMATCHER_SRC_REPO_NAME:?err}
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
  dependencies-doc:
    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher-dependencies-doc:${LPM_IMAGE_TAG:?err}
    build:
      context: ..
      dockerfile: ./build_system/ubuntu/Dockerfile.dependencies_doc
      platforms:
        - "linux/amd64"
        - "linux/arm64/v8"
      args:
        PROJECT_HUB: ${LPM_PROJECT_DOCKERHUB}
        BASE_IMAGE: libpointmatcher-dependencies
        BASE_IMAGE_TAG: ${LPM_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
    tty: true
    stdin_open: true
  ci_PR:
    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher-ci-pr:${LPM_IMAGE_TAG:?err}
    pull_policy: build
    build:
      context: ..
      dockerfile: './build_system/ubuntu/Dockerfile.libpointmatcher_ci_PR'
      no_cache: true
      args:
        PROJECT_HUB: ${LPM_PROJECT_DOCKERHUB}
        BASE_IMAGE: libpointmatcher-dependencies
        BASE_IMAGE_TAG: ${LPM_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        LIBPOINTMATCHER_VERSION: 'head'
        LIBPOINTMATCHER_CMAKE_BUILD_TYPE: ${LIBPOINTMATCHER_CMAKE_BUILD_TYPE:?err}
        LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG: '--build-system-CI-install --compile-test'
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
  ci_PR_amd64:
    extends: ci_PR
    platform: "linux/amd64"
  ci_PR_arm64v8:
    extends: ci_PR
    platform: "linux/arm64/v8"
  ci_SITREP_matrix:
    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher-ci-sitrep-matrix:${LPM_IMAGE_TAG:?err}
    pull_policy: build
    build:
      context: ..
      dockerfile: './build_system/ubuntu/Dockerfile.libpointmatcher_ci_SITREP_matrix'
      no_cache: true
      args:
        PROJECT_HUB: ${LPM_PROJECT_DOCKERHUB}
        BASE_IMAGE: libpointmatcher-dependencies
        BASE_IMAGE_TAG: ${LPM_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        LIBPOINTMATCHER_VERSION: ${LIBPOINTMATCHER_VERSION:?err}
        LIBPOINTMATCHER_CMAKE_BUILD_TYPE: ${LIBPOINTMATCHER_CMAKE_BUILD_TYPE:?err}
        LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG: '--compile-test'
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
  ci_SITREP_matrix_amd64:
    extends: ci_SITREP_matrix
    platform: "linux/amd64"
  ci_SITREP_matrix_arm64v8:
    extends: ci_SITREP_matrix
    platform: "linux/arm64/v8"
  release:
    image: ${LPM_PROJECT_DOCKERHUB:?err}/libpointmatcher:${LPM_IMAGE_TAG:?err}
    container_name: libpointmatcher
    build:
      context: ..
      dockerfile: ./build_system/ubuntu/Dockerfile.libpointmatcher
      platforms:
        - "linux/amd64"
        - "linux/arm64/v8"
      no_cache: true
      args:
        PROJECT_HUB: ${LPM_PROJECT_DOCKERHUB}
        BASE_IMAGE: libpointmatcher-dependencies-doc
        BASE_IMAGE_TAG: ${LPM_IMAGE_TAG}
        IS_TEAMCITY_RUN: ${IS_TEAMCITY_RUN}
        LIBPOINTMATCHER_VERSION: ${LIBPOINTMATCHER_VERSION:?err}
        LIBPOINTMATCHER_CMAKE_BUILD_TYPE: 'Release'
        LIBPOINTMATCHER_INSTALL_SCRIPT_FLAG: '--compile-test --generate-doc'
    tty: true
    stdin_open: true
    init: true  # Propagate exit code (See remark in task NMO-266)
    depends_on:
      - dependencies
      - dependencies-doc


